import { jsPDF } from "jspdf";

export interface PDFQuestion {
    question: string;
    topic?: string;
    answer?: any[] | string;
    type?: 'mcq' | 'fb' | 'desc';
    options?: string[];
    correctAnswer?: string | number;
}

export interface PDFUnitData {
    title: string;
    unit: string | number;
    subjectName: string;
    mcqs: PDFQuestion[];
    fillBlanks: PDFQuestion[];
    descriptives: PDFQuestion[];
    options?: {
        includeAnswers: boolean;
        includeExplanations: boolean;
    }
}

// --- Psychological & Aesthetic Constants ---
const COLORS = {
    PRIMARY: [79, 70, 229],    // Indigo (Focus & Authority)
    SECONDARY: [124, 58, 237], // Purple (Creativity)
    TEXT: [15, 23, 42],       // Slate 900 (Deep Contrast)
    MUTED: [71, 85, 105],     // Slate 600 (Clear Labels)
    ACCENT: [5, 150, 105],    // Emerald 600 (Stronger Correct)
    BG_CARD: [241, 245, 249],  // Slate 100 (Visible Chunking)
    BORDER: [51, 65, 85],     // Slate 700 (Dark/Strong Dividers)
};

export const generateUnitPDF = (data: PDFUnitData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);
    let y = margin;

    const checkPageBreak = (needed: number) => {
        if (y + needed > pageHeight - margin - 15) { // Leave room for footer
            doc.addPage();
            y = margin + 10;
            addPageHeader();
        }
    };

    const addPageHeader = () => {
        doc.setFontSize(8);
        doc.setTextColor(...(COLORS.MUTED as [number, number, number]));
        doc.text(`NullPtr Learning Material • ${data.subjectName}`, margin, 10);
        const pageNum = (doc as any).internal.getNumberOfPages();
        doc.text(`Page ${pageNum}`, pageWidth - margin - 15, 10);
        doc.setDrawColor(...(COLORS.BORDER as [number, number, number]));
        doc.line(margin, 12, pageWidth - margin, 12);
    };

    const addPageFooter = (sectionName: string) => {
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(...(COLORS.MUTED as [number, number, number]));
            doc.text(`Focus Area: ${sectionName}`, margin, pageHeight - 10);
            doc.text("Generated by NullPtr AI", pageWidth - margin - 35, pageHeight - 10);
        }
    };

    // --- High-Wow Title Page (Psychological Priming) ---
    // Background Decoration
    doc.setFillColor(...(COLORS.BG_CARD as [number, number, number]));
    doc.rect(0, 0, pageWidth, pageHeight, 'F');

    doc.setFillColor(...(COLORS.PRIMARY as [number, number, number]));
    doc.rect(0, 0, pageWidth, 5, 'F'); // Top accent bar

    y = 60;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(36);
    doc.setTextColor(...(COLORS.PRIMARY as [number, number, number]));
    doc.text("STUDY", margin, y);
    doc.text("GUIDE", margin, y + 14);

    y += 40;
    doc.setFontSize(14);
    doc.setTextColor(...(COLORS.MUTED as [number, number, number]));
    doc.text("ENGINEERED LEARNING MATERIAL", margin, y);

    y += 15;
    doc.setFontSize(28);
    doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
    doc.text(data.subjectName.toUpperCase(), margin, y);

    y += 15;
    doc.setFontSize(16);
    doc.setTextColor(...(COLORS.SECONDARY as [number, number, number]));
    doc.text(`Unit ${data.unit}: ${data.title}`, margin, y);

    y += 15;
    doc.setDrawColor(...(COLORS.PRIMARY as [number, number, number]));
    doc.setLineWidth(1.5);
    doc.line(margin, y, margin + 60, y);

    // Objective Section (Signal Importance)
    y += 40;
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(...(COLORS.BORDER as [number, number, number]));
    doc.rect(margin, y, contentWidth, 50, 'FD');

    doc.setFontSize(10);
    doc.setTextColor(...(COLORS.MUTED as [number, number, number]));
    doc.text("LEARNING OBJECTIVE", margin + 10, y + 15);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
    const objectiveText = `This guide provides a structured breakdown of ${data.title}, optimized for cognitive retention and technical clarity. Focus on the diagrams and highlighted key concepts for maximum effectiveness.`;
    const objLines = doc.splitTextToSize(objectiveText, contentWidth - 20);
    doc.text(objLines, margin + 10, y + 25);

    doc.addPage();
    y = margin + 10;
    addPageHeader();

    const renderSection = (title: string, questions: PDFQuestion[], iconColor: number[]) => {
        if (!questions || questions.length === 0) return;

        checkPageBreak(40);

        // --- Section Title (Typographic Authority) ---
        doc.setFont("helvetica", "bold");
        doc.setFontSize(24);
        doc.setTextColor(...(COLORS.PRIMARY as [number, number, number]));
        doc.text(title, margin + 8, y);

        // Solid Section Marker (Bullet-proof)
        doc.setFillColor(...iconColor as [number, number, number]);
        doc.rect(margin, y - 6, 4, 8, 'F');

        y += 6;
        doc.setDrawColor(...(COLORS.PRIMARY as [number, number, number]));
        doc.setLineWidth(1.5);
        doc.line(margin, y, margin + 60, y);
        y += 20;

        questions.forEach((q, idx) => {
            // Calculate Question Height (Sweet spot: 13pt)
            doc.setFont("helvetica", "bold");
            doc.setFontSize(13);
            const qLines = doc.splitTextToSize(`${idx + 1}. ${q.question}`, contentWidth - 10);
            const qBlockHeight = (qLines.length * 8) + 10;

            checkPageBreak(qBlockHeight + 30);

            // --- Question Block (Balanced Shading) ---
            doc.setFillColor(...(COLORS.BG_CARD as [number, number, number]));
            doc.rect(margin, y, contentWidth, qBlockHeight, 'F');

            doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
            doc.text(qLines, margin + 5, y + 10);
            y += qBlockHeight + 8;

            // Optional Topic
            if (q.topic) {
                doc.setFont("helvetica", "bold");
                doc.setFontSize(8);
                doc.setTextColor(...(COLORS.MUTED as [number, number, number]));
                doc.text(`SUBJECT TOPIC: ${q.topic.toUpperCase()}`, margin + 5, y);
                y += 8;
            }

            // Options (for MCQs)
            if (q.options && q.options.length > 0) {
                doc.setFont("helvetica", "normal");
                doc.setFontSize(10.5);
                doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
                q.options.forEach((opt, oIdx) => {
                    const char = String.fromCharCode(65 + oIdx);
                    checkPageBreak(10);
                    doc.text(`${char}) ${opt}`, margin + 10, y);
                    y += 7; // Adjusted for 1.4x line height
                });
                y += 6;
            }

            // Answer Content
            if (q.answer && Array.isArray(q.answer)) {
                q.answer.forEach(block => {
                    doc.setFont("helvetica", "normal");

                    switch (block.type) {
                        case 'heading':
                            y += 4;
                            doc.setFont("helvetica", "bold");
                            doc.setFontSize(12);
                            doc.setTextColor(...(COLORS.PRIMARY as [number, number, number]));
                            checkPageBreak(12);
                            doc.text(block.content, margin + 5, y);
                            y += 8;
                            break;
                        case 'subheading':
                            doc.setFont("helvetica", "bold");
                            doc.setFontSize(11);
                            doc.setTextColor(...(COLORS.SECONDARY as [number, number, number]));
                            checkPageBreak(10);
                            doc.text(block.content, margin + 5, y);
                            y += 7;
                            break;
                        case 'text':
                            doc.setFont("helvetica", "normal");
                            doc.setFontSize(10.5);
                            doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
                            const textLines = doc.splitTextToSize(block.content, contentWidth - 10);
                            const lineSpacing = 7; // 1.4x of 10.5 is 14.7, splitText usually uses font size + leading
                            checkPageBreak(textLines.length * lineSpacing + 6);
                            doc.text(textLines, margin + 5, y);
                            y += (textLines.length * lineSpacing) + 6;
                            break;
                        case 'list':
                            doc.setFont("helvetica", "normal");
                            doc.setFontSize(10.5);
                            doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
                            block.items.forEach((item: string) => {
                                const itemLines = doc.splitTextToSize(`> ${item}`, contentWidth - 15);
                                checkPageBreak(itemLines.length * 6.5 + 4);
                                doc.text(itemLines, margin + 10, y);
                                y += (itemLines.length * 6.5);
                            });
                            y += 5;
                            break;
                        case 'code':
                            doc.setFont("courier", "normal");
                            doc.setFontSize(9);
                            doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
                            const codeLines = block.content.split('\n');
                            const boxHeight = (codeLines.length * 5) + 10;
                            checkPageBreak(boxHeight + 8);

                            doc.setFillColor(...(COLORS.BG_CARD as [number, number, number]));
                            doc.setDrawColor(...(COLORS.BORDER as [number, number, number]));
                            doc.setLineWidth(0.5);
                            doc.rect(margin + 5, y - 4, contentWidth - 10, boxHeight, 'FD');

                            codeLines.forEach((line: string) => {
                                doc.text(line, margin + 10, y + 2);
                                y += 5;
                            });
                            y += 10;
                            break;
                    }
                });
            } else if (q.correctAnswer !== undefined && data.options?.includeAnswers) {
                doc.setFont("helvetica", "bold");
                doc.setFontSize(11);
                doc.setTextColor(...(COLORS.ACCENT as [number, number, number]));
                const ansText = q.type === 'mcq'
                    ? `[Verified] Correct Option: ${String.fromCharCode(64 + (Number(q.correctAnswer) + 1))}`
                    : `[Verified] Correct Answer: ${q.correctAnswer}`;

                checkPageBreak(12);
                doc.text(ansText, margin + 5, y);
                y += 12;
            } else if (typeof q.answer === 'string' && q.answer) {
                doc.setFont("helvetica", "normal");
                doc.setFontSize(10.5);
                doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
                const ansLines = doc.splitTextToSize(`Ans: ${q.answer}`, contentWidth - 10);
                const lineSpacing = 7;
                checkPageBreak(ansLines.length * lineSpacing + 8);
                doc.text(ansLines, margin + 5, y);
                y += (ansLines.length * lineSpacing) + 8;
            }

            // --- Dark Divider (High Contrast Separation) ---
            y += 4;
            doc.setDrawColor(...(COLORS.BORDER as [number, number, number]));
            doc.setLineWidth(0.5);
            doc.line(margin, y, pageWidth - margin, y);
            y += 15;
        });

        y += 10;
    };

    renderSection("Multiple Choice Questions", data.mcqs, COLORS.SECONDARY);
    renderSection("Fill in the Blanks", data.fillBlanks, COLORS.SECONDARY);
    renderSection("Detailed Explanations", data.descriptives, COLORS.PRIMARY);

    addPageFooter(data.title.toString());

    doc.save(`${data.subjectName}_Unit${data.unit}_StudyGuide.pdf`);
};
