import { jsPDF } from "jspdf";

export interface PDFQuestion {
    question: string;
    topic?: string;
    answer?: any[] | string;
    type?: 'mcq' | 'fb' | 'desc';
    options?: string[];
    correctAnswer?: string | number;
}

export interface PDFUnitData {
    title: string;
    unit: string | number;
    subjectName: string;
    mcqs: PDFQuestion[];
    fillBlanks: PDFQuestion[];
    descriptives: PDFQuestion[];
    options?: {
        includeAnswers: boolean;
        includeExplanations: boolean;
    }
}

// --- Psychological & Aesthetic Constants ---
const COLORS = {
    PRIMARY: [79, 70, 229],    // Indigo (Focus & Authority)
    SECONDARY: [124, 58, 237], // Purple (Creativity)
    TEXT: [30, 41, 59],       // Slate 800 (Contrast)
    MUTED: [100, 116, 139],    // Slate 500 (Cleanliness)
    ACCENT: [16, 185, 129],    // Emerald (Success/Correct)
    BG_CARD: [248, 250, 252],  // Slate 50 (Chunking Background)
    BORDER: [226, 232, 240],   // Slate 200 (Subtle Separation)
};

export const generateUnitPDF = (data: PDFUnitData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);
    let y = margin;

    const checkPageBreak = (needed: number) => {
        if (y + needed > pageHeight - margin - 15) { // Leave room for footer
            doc.addPage();
            y = margin + 10;
            addPageHeader();
        }
    };

    const addPageHeader = () => {
        doc.setFontSize(8);
        doc.setTextColor(...(COLORS.MUTED as [number, number, number]));
        doc.text(`NullPtr Learning Material • ${data.subjectName}`, margin, 10);
        const pageNum = (doc as any).internal.getNumberOfPages();
        doc.text(`Page ${pageNum}`, pageWidth - margin - 15, 10);
        doc.setDrawColor(...(COLORS.BORDER as [number, number, number]));
        doc.line(margin, 12, pageWidth - margin, 12);
    };

    const addPageFooter = (sectionName: string) => {
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(...(COLORS.MUTED as [number, number, number]));
            doc.text(`Focus Area: ${sectionName}`, margin, pageHeight - 10);
            doc.text("Generated by NullPtr AI", pageWidth - margin - 35, pageHeight - 10);
        }
    };

    // --- High-Wow Title Page (Psychological Priming) ---
    // Background Decoration
    doc.setFillColor(...(COLORS.BG_CARD as [number, number, number]));
    doc.rect(0, 0, pageWidth, pageHeight, 'F');

    doc.setFillColor(...(COLORS.PRIMARY as [number, number, number]));
    doc.rect(0, 0, pageWidth, 5, 'F'); // Top accent bar

    y = 60;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(36);
    doc.setTextColor(...(COLORS.PRIMARY as [number, number, number]));
    doc.text("STUDY", margin, y);
    doc.text("GUIDE", margin, y + 14);

    y += 40;
    doc.setFontSize(14);
    doc.setTextColor(...(COLORS.MUTED as [number, number, number]));
    doc.text("ENGINEERED LEARNING MATERIAL", margin, y);

    y += 15;
    doc.setFontSize(28);
    doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
    doc.text(data.subjectName.toUpperCase(), margin, y);

    y += 15;
    doc.setFontSize(16);
    doc.setTextColor(...(COLORS.SECONDARY as [number, number, number]));
    doc.text(`Unit ${data.unit}: ${data.title}`, margin, y);

    y += 15;
    doc.setDrawColor(...(COLORS.PRIMARY as [number, number, number]));
    doc.setLineWidth(1.5);
    doc.line(margin, y, margin + 60, y);

    // Objective Section (Signal Importance)
    y += 40;
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(...(COLORS.BORDER as [number, number, number]));
    doc.rect(margin, y, contentWidth, 50, 'FD');

    doc.setFontSize(10);
    doc.setTextColor(...(COLORS.MUTED as [number, number, number]));
    doc.text("LEARNING OBJECTIVE", margin + 10, y + 15);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
    const objectiveText = `This guide provides a structured breakdown of ${data.title}, optimized for cognitive retention and technical clarity. Focus on the diagrams and highlighted key concepts for maximum effectiveness.`;
    const objLines = doc.splitTextToSize(objectiveText, contentWidth - 20);
    doc.text(objLines, margin + 10, y + 25);

    doc.addPage();
    y = margin + 10;
    addPageHeader();

    const renderSection = (title: string, questions: PDFQuestion[], icon: string) => {
        if (!questions || questions.length === 0) return;

        checkPageBreak(30);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(18);
        doc.setTextColor(...(COLORS.PRIMARY as [number, number, number]));

        // --- Section Title ---
        doc.text(`${icon} ${title.toUpperCase()}`, margin, y);
        y += 4;
        doc.setDrawColor(...(COLORS.PRIMARY as [number, number, number]));
        doc.setLineWidth(1);
        doc.line(margin, y, margin + 25, y);
        y += 12;

        questions.forEach((q, idx) => {
            // 1. Calculate Question Height
            doc.setFont("helvetica", "bold");
            doc.setFontSize(10);
            const qLines = doc.splitTextToSize(`${q.question}`, contentWidth - 25);
            const qHeaderHeight = (qLines.length * 5) + 12;

            // 2. Check Page Break
            checkPageBreak(qHeaderHeight + 20); // Minimum space for Header + Start of Answer

            const cardStartY = y;

            // --- Question Header Box (Instructional Contrast) ---
            doc.setFillColor(...(COLORS.PRIMARY as [number, number, number]));
            doc.rect(margin, y, contentWidth, qHeaderHeight, 'F');

            // Q-Badge
            doc.setFillColor(255, 255, 255);
            doc.rect(margin + 4, y + 4, 8, 8, 'F');
            doc.setFontSize(8);
            doc.setTextColor(...(COLORS.PRIMARY as [number, number, number]));
            doc.text("Q", margin + 6, y + 9.5);

            // Question Text (White for high contrast)
            doc.setFont("helvetica", "bold");
            doc.setFontSize(10);
            doc.setTextColor(255, 255, 255);
            doc.text(qLines, margin + 16, y + 9);

            y += qHeaderHeight;

            // --- Answer Area ---
            const answerAreaStartY = y;
            y += 8; // Padding top

            // Optional Topic (Mini-badge)
            if (q.topic) {
                doc.setFont("helvetica", "bold");
                doc.setFontSize(7);
                doc.setTextColor(...(COLORS.MUTED as [number, number, number]));
                doc.text(`SUBJECT TOPIC: ${q.topic.toUpperCase()}`, margin + 5, y);
                y += 6;
            }

            // Options (for MCQs)
            if (q.options && q.options.length > 0) {
                doc.setFont("helvetica", "normal");
                doc.setFontSize(10);
                doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
                q.options.forEach((opt, oIdx) => {
                    const char = String.fromCharCode(65 + oIdx);
                    checkPageBreak(10);
                    doc.text(`${char}) ${opt}`, margin + 10, y);
                    y += 6;
                });
                y += 4;
            }

            // Answer Content (Block-elements / Specific Answers)
            const renderAnswerBadge = () => {
                doc.setFont("helvetica", "bold");
                doc.setFontSize(8);
                doc.setTextColor(...(COLORS.ACCENT as [number, number, number]));
                doc.text("EXPLANATION / ANSWER:", margin + 5, y);
                y += 6;
            };

            if (q.answer && Array.isArray(q.answer)) {
                renderAnswerBadge();
                q.answer.forEach(block => {
                    doc.setFont("helvetica", "normal");

                    switch (block.type) {
                        case 'heading':
                            y += 2;
                            doc.setFont("helvetica", "bold");
                            doc.setFontSize(10);
                            doc.setTextColor(...(COLORS.PRIMARY as [number, number, number]));
                            checkPageBreak(10);
                            doc.text(block.content, margin + 5, y);
                            y += 6;
                            break;
                        case 'subheading':
                            doc.setFont("helvetica", "bold");
                            doc.setFontSize(9);
                            doc.setTextColor(...(COLORS.SECONDARY as [number, number, number]));
                            checkPageBreak(8);
                            doc.text(block.content, margin + 5, y);
                            y += 5;
                            break;
                        case 'text':
                            doc.setFont("helvetica", "normal");
                            doc.setFontSize(10);
                            doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
                            const textLines = doc.splitTextToSize(block.content, contentWidth - 10);
                            checkPageBreak(textLines.length * 5.5 + 4);
                            doc.text(textLines, margin + 5, y);
                            y += (textLines.length * 5.5) + 3;
                            break;
                        case 'list':
                            doc.setFont("helvetica", "normal");
                            doc.setFontSize(10);
                            doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
                            block.items.forEach((item: string) => {
                                const itemLines = doc.splitTextToSize(`• ${item}`, contentWidth - 15);
                                checkPageBreak(itemLines.length * 5.5 + 2);
                                doc.text(itemLines, margin + 10, y);
                                y += (itemLines.length * 5.5);
                            });
                            y += 3;
                            break;
                        case 'code':
                            doc.setFont("courier", "normal");
                            doc.setFontSize(9);
                            doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
                            const codeLines = block.content.split('\n');
                            const boxHeight = (codeLines.length * 4.5) + 6;
                            checkPageBreak(boxHeight + 5);

                            doc.setFillColor(...(COLORS.BG_CARD as [number, number, number]));
                            doc.setDrawColor(...(COLORS.BORDER as [number, number, number]));
                            doc.rect(margin + 5, y - 4, contentWidth - 10, boxHeight, 'FD');

                            codeLines.forEach((line: string) => {
                                doc.text(line, margin + 9, y);
                                y += 4.5;
                            });
                            y += 6;
                            break;
                    }
                });
            } else if (q.correctAnswer !== undefined && data.options?.includeAnswers) {
                doc.setFont("helvetica", "bold");
                doc.setFontSize(10);
                doc.setTextColor(...(COLORS.ACCENT as [number, number, number]));
                const ansText = q.type === 'mcq'
                    ? `✔ CORRECT OPTION: ${String.fromCharCode(64 + (Number(q.correctAnswer) + 1))}`
                    : `✔ CORRECT ANSWER: ${q.correctAnswer}`;

                checkPageBreak(10);
                doc.text(ansText, margin + 5, y);
                y += 8;
            } else if (typeof q.answer === 'string' && q.answer) {
                renderAnswerBadge();
                doc.setFont("helvetica", "normal");
                doc.setFontSize(10);
                doc.setTextColor(...(COLORS.TEXT as [number, number, number]));
                const ansLines = doc.splitTextToSize(q.answer, contentWidth - 10);
                checkPageBreak(ansLines.length * 5.5 + 5);
                doc.text(ansLines, margin + 5, y);
                y += (ansLines.length * 5.5) + 4;
            }

            const cardEndY = y;

            // --- Draw Learning Card Border (Absolute Separation) ---
            doc.setDrawColor(...(COLORS.BORDER as [number, number, number]));
            doc.setLineWidth(0.5);
            doc.rect(margin, cardStartY, contentWidth, cardEndY - cardStartY, 'D');

            y += 12; // Gap between cards
        });

        y += 10;
    };

    renderSection("Multiple Choice Questions", data.mcqs, "●");
    renderSection("Fill in the Blanks", data.fillBlanks, "✎");
    renderSection("Detailed Explanations", data.descriptives, "📖");

    addPageFooter(data.title.toString());

    doc.save(`${data.subjectName}_Unit${data.unit}_StudyGuide.pdf`);
};
